---
## Version-specific settings that override the values in cfg/config.yaml

master:
  components:
    - apiserver
    - scheduler
    - controllermanager
    - etcd
    - policies

  apiserver:
    bins:
      - containerd
    defaultconf: /var/snap/microk8s/current/args/kube-apiserver

  scheduler:
    bins:
      - containerd
    defaultconf: /var/snap/microk8s/current/args/kube-scheduler

  controllermanager:
    bins:
      - containerd
    defaultconf: /var/snap/microk8s/current/args/kube-controller-manager

  etcd:
    bins:
      - containerd
    confs:
      - /var/snap/microk8s/current/args/k8s-dqlite
    defaultconf: /var/snap/microk8s/current/args/k8s-dqlite
    defaultdatadir: /var/snap/microk8s/current/var/kubernetes/backend

node:
  components:
    - kubelet
    - proxy

  kubelet:
    bins:
      - containerd
    svc:
      # These paths must also be included
      #  in the 'confs' property below
      - "/etc/systemd/system/snap.kubelet.daemon.service"
      - "/etc/systemd/system/snap.microk8s.daemon-kubelet.service"
    defaultkubeconfig: /var/snap/microk8s/current/credentials/kubelet.config
    defaultcafile: /var/snap/microk8s/current/certs/ca.crt

  proxy:
    bins:
      - containerd
    defaultkubeconfig: /var/snap/microk8s/current/credentials/proxy.config

etcd:
  components:
    - etcd

  etcd:
    bins:
      - etcd
      - containerd
    confs:
      - /var/snap/microk8s/current/args/k8s-dqlite
    defaultconf: /var/snap/microk8s/current/args/k8s-dqlite
    defaultdatadir: /var/snap/microk8s/current/var/kubernetes/backend

policies:
  components:
    - policies
